# Generated by Django 5.0.6 on 2024-05-24 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aform_app', '0001_initial'),
        ('user_app', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='user_app.organization'),
        ),
    ]
