# Generated by Django 5.0.6 on 2024-05-25 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aform_app', '0002_form_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_multiple_selection', models.BooleanField(default=False)),
                ('randomize', models.BooleanField(default=False)),
                ('allow_other_choice', models.CharField(blank=True, max_length=100, null=True)),
                ('vertical_alignment', models.BooleanField(default=True)),
                ('supersized', models.BooleanField(default=False)),
                ('show_labels', models.BooleanField(default=True)),
                ('alphabetical_order', models.BooleanField(default=False)),
                ('hide_marks', models.BooleanField(default=True)),
                ('button_text', models.CharField(default='Continue')),
                ('steps', models.IntegerField(default=10)),
                ('shape', models.CharField(choices=[(1, 'star')], default=1)),
                ('start_at_one', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('lables', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('ref', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[(1, 'short_question'), (2, 'long_question'), (3, 'email'), (4, 'website'), (5, 'address'), (6, 'phone'), (7, 'multi_choice'), (8, 'dropdown'), (9, 'yes_no'), (10, 'legal'), (11, 'number'), (12, 'date'), (13, 'ranking'), (14, 'rating')], default='short_question')),
                ('layout', models.JSONField(blank=True, null=True)),
                ('properties', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aform_app.fieldproperty')),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aform_app.form')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aform_app.field')),
            ],
            options={
                'unique_together': {('form', 'field')},
            },
        ),
        migrations.AddField(
            model_name='form',
            name='fields',
            field=models.ManyToManyField(through='aform_app.FormField', to='aform_app.field'),
        ),
    ]
