# Generated by Django 5.0.6 on 2024-05-26 17:41

import aform_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aform_app', '0002_form_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_multiple_selection', models.BooleanField(default=False)),
                ('randomize', models.BooleanField(default=False)),
                ('allow_other_choice', models.CharField(blank=True, max_length=100, null=True)),
                ('vertical_alignment', models.BooleanField(default=True)),
                ('supersized', models.BooleanField(default=False)),
                ('show_labels', models.BooleanField(default=True)),
                ('alphabetical_order', models.BooleanField(default=False)),
                ('hide_marks', models.BooleanField(default=True)),
                ('button_text', models.CharField(default='Continue')),
                ('steps', models.IntegerField(default=10)),
                ('shape', models.CharField(choices=[(1, 'star')], default=1)),
                ('start_at_one', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('lables', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('equal', 'equal'), ('is', 'is'), ('is_not', 'is_not'), ('greater', 'greater'), ('less_than', 'less_than'), ('and', 'and'), ('or', 'or')], max_length=10)),
                ('order', models.IntegerField(default=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='aform_app.condition')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vars', to='aform_app.condition')),
            ],
        ),
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(aform_app.models.Field, 'field'), (2, 'hidden')], default=1)),
                ('ref', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logic', to='aform_app.form')),
            ],
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('jump', 'jump'), ('add', 'add'), ('subtract', 'subtract'), ('multiply', 'multiply'), ('divide', 'divide')])),
                ('details', models.JSONField()),
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='aform_app.condition')),
                ('logic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='aform_app.logic')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('ref', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(1, 'short_question'), (2, 'long_question'), (3, 'email'), (4, 'website'), (5, 'address'), (6, 'phone'), (7, 'multi_choice'), (8, 'dropdown'), (9, 'yes_no'), (10, 'legal'), (11, 'number'), (12, 'date'), (13, 'ranking'), (14, 'rating')], default='short_question')),
                ('layout', models.JSONField(blank=True, null=True)),
                ('properties', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aform_app.fieldproperty')),
                ('order', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='aform_app.form')),
            ],
        ),
    ]
