# Generated by Django 5.0.6 on 2024-05-27 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aform_app', '0003_fieldproperty_condition_conditionvariable_logic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='type',
            new_name='action',
        ),
        migrations.AlterField(
            model_name='actions',
            name='condition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='aform_app.condition'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='logic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='aform_app.logic'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='operator',
            field=models.CharField(blank=True, choices=[('equal', 'equal'), ('is', 'is'), ('is_not', 'is_not'), ('greater', 'greater'), ('less_than', 'less_than'), ('and', 'and'), ('or', 'or')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='conditionvariable',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vars', to='aform_app.condition'),
        ),
        migrations.AlterField(
            model_name='field',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='aform_app.form'),
        ),
    ]
