# Generated by Django 5.0.6 on 2024-05-27 18:20

import aform_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aform_app', '0004_rename_type_actions_action_alter_actions_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logic',
            name='type',
            field=models.CharField(choices=[(aform_app.models.Field, 'field'), ('constant', 'hidden')], default='field'),
        ),
    ]
