# Generated by Django 5.0.6 on 2024-05-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aform_app', '0005_alter_logic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logic',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logic', to='aform_app.form'),
        ),
    ]
