# Generated by Django 5.0.6 on 2024-06-08 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aform_app', '0006_alter_logic_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vars', to='aform_app.condition'),
        ),
        migrations.DeleteModel(
            name='ConditionVariable',
        ),
    ]
