# Generated by Django 5.0.6 on 2024-06-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aform_app', '0007_condition_type_condition_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='description',
        ),
        migrations.AddField(
            model_name='fieldproperty',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
