# Generated by Django 5.0.6 on 2024-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aform_app', '0008_remove_field_description_fieldproperty_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logic',
            name='type',
            field=models.CharField(choices=[('field', 'field'), ('constant', 'hidden')], default='field'),
        ),
    ]
