# Generated by Django 5.0.6 on 2024-06-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aform_app', '0009_alter_logic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vars', to='aform_app.condition'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
