# Generated by Django 5.0.6 on 2024-06-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aform_app', '0010_alter_condition_parent_alter_condition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='operator',
            field=models.CharField(blank=True, choices=[('equal', 'equal'), ('is', 'is'), ('is_not', 'is_not'), ('greater', 'greater'), ('less_than', 'less_than'), ('and', 'and'), ('or', 'or'), ('contains', 'contains')], max_length=10, null=True),
        ),
    ]
